name: Update LiveContainer Stable

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch Latest Stable
        run: |
          mkdir -p apps/utilities
          
          # جلب رقم الإصدار فقط عشان نكتبه في المتجر
          API_URL="https://api.github.com/repos/LiveContainer/LiveContainer/releases/latest"
          REAL_VERSION=$(curl -s "$API_URL" | jq -r '.tag_name' | sed 's/^v//')
          
          if [ "$REAL_VERSION" == "null" ] || [ -z "$REAL_VERSION" ]; then
            REAL_VERSION="Stable"
          fi
          echo "Version: $REAL_VERSION"

          # استخدام الرابط المباشر والثابت اللي أرسلته
          DOWNLOAD_URL="https://github.com/LiveContainer/LiveContainer/releases/latest/download/LiveContainer+SideStore.ipa"
          
          echo "Downloading from direct link..."
          curl -L "$DOWNLOAD_URL" -o apps/utilities/livecontainer_stable.ipa
          echo "$REAL_VERSION" > version.txt

      - name: Upload to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload nightly apps/utilities/livecontainer_stable.ipa --clobber || gh release create nightly apps/utilities/livecontainer_stable.ipa --clobber

      - name: Update JSON Data
        run: |
          REAL_VERSION=$(cat version.txt)
          DATE_NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          FILESIZE=$(stat -c%s "apps/utilities/livecontainer_stable.ipa" || echo "35000000")
          
          jq --arg version "$REAL_VERSION" \
             --arg date "$DATE_NOW" \
             --argjson size "$FILESIZE" \
             '(.apps[] | select(.name == "LiveContainer (Stable)")).versions[0] |= . + {version: $version, date: $date, size: $size}' repo.json > temp.json && mv temp.json repo.json

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add repo.json
          git commit -m "Auto-update LiveContainer Stable to Version $REAL_VERSION" || echo "No changes"
          git push
