name: Update ALL Apps

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Workflows Sequentially
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Starting update queue..."
          gh workflow run amethyst.yml || true
          echo "Amethyst triggered. Waiting 120 seconds..."
          sleep 120
          
          gh workflow run dolphinios.yml || true
          echo "DolphiniOS triggered. Waiting 120 seconds..."
          sleep 120
          
          gh workflow run getmoreram.yml || true
          echo "GetMoreRam triggered. Waiting 120 seconds..."
          sleep 120
          
          gh workflow run ipsx2.yml || true
          echo "iPSX2 triggered. Waiting 120 seconds..."
          sleep 120
          
          gh workflow run manic.yml || true
          echo "Manic triggered. Waiting 120 seconds..."
          sleep 120
          
          gh workflow run melonx.yml || true
          echo "MeloNX triggered. Waiting 120 seconds..."
          sleep 120
          
          gh workflow run ppsspp.yml || true
          echo "PPSSPP triggered. Waiting 120 seconds..."
          sleep 120
          
          gh workflow run xenios.yml || true
          echo "Xenios triggered! Queue completed."
