 name: 🔄 Update ALL Apps

on:
  schedule:
    - cron: "0 */12 * * *" # المدير هو الذي سيعمل تلقائياً كل 12 ساعة
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Workflows Sequentially (Queue)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Starting update queue..."
          gh workflow run amethyst.yml
          echo "Amethyst triggered. Waiting 60 seconds..."
          sleep 120
          
          gh workflow run dolphinios.yml
          echo "DolphiniOS triggered. Waiting 60 seconds..."
          sleep 120
          
          gh workflow run getmoreram.yml
          echo "GetMoreRam triggered. Waiting 60 seconds..."
          sleep 120
          
          gh workflow run ipsx2.yml
          echo "iPSX2 triggered. Waiting 60 seconds..."
          sleep 120
          
          gh workflow run manic.yml
          echo "Manic triggered. Waiting 60 seconds..."
          sleep 120
          
          gh workflow run melonx.yml
          echo "MeloNX triggered. Waiting 60 seconds..."
          sleep 120
          
          gh workflow run ppsspp.yml
          echo "PPSSPP triggered. Waiting 60 seconds..."
          sleep 120
          
          gh workflow run xenios.yml
          echo "Xenios triggered! Queue completed."
